//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoBuildBot.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoBuildBot.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Account.
        /// </summary>
        public static string B_Account {
            get {
                return ResourceManager.GetString("B_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭕️ ALL APPLICABLE RINGS.
        /// </summary>
        public static string B_AllApplicableRings {
            get {
                return ResourceManager.GetString("B_AllApplicableRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭕️ ALL DEVICE FAMILIES.
        /// </summary>
        public static string B_AllDeviceFamilies {
            get {
                return ResourceManager.GetString("B_AllDeviceFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭕️ ALL RINGS.
        /// </summary>
        public static string B_AllRings {
            get {
                return ResourceManager.GetString("B_AllRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❕ ALL SUBSCRIBED.
        /// </summary>
        public static string B_AllSubscribed {
            get {
                return ResourceManager.GetString("B_AllSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❗️ ALL UNSUBSCRIBED.
        /// </summary>
        public static string B_AllUnsubscribed {
            get {
                return ResourceManager.GetString("B_AllUnsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀️ Back.
        /// </summary>
        public static string B_Back {
            get {
                return ResourceManager.GetString("B_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Bot Settings.
        /// </summary>
        public static string B_BotSettings {
            get {
                return ResourceManager.GetString("B_BotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗣 Change Language.
        /// </summary>
        public static string B_ChangeLanguage {
            get {
                return ResourceManager.GetString("B_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Delete account.
        /// </summary>
        public static string B_DeleteAccount {
            get {
                return ResourceManager.GetString("B_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭕️ EVERYTHING.
        /// </summary>
        public static string B_Everything {
            get {
                return ResourceManager.GetString("B_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 Group settings.
        /// </summary>
        public static string B_GroupSettings {
            get {
                return ResourceManager.GetString("B_GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📨 Notifications.
        /// </summary>
        public static string B_Notifications {
            get {
                return ResourceManager.GetString("B_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Search.
        /// </summary>
        public static string B_Search {
            get {
                return ResourceManager.GetString("B_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Search updates now!.
        /// </summary>
        public static string B_SearchNow {
            get {
                return ResourceManager.GetString("B_SearchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏘 Start page.
        /// </summary>
        public static string B_Start {
            get {
                return ResourceManager.GetString("B_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☑️ SUBSCRIBE ALL.
        /// </summary>
        public static string B_SubscribeAll {
            get {
                return ResourceManager.GetString("B_SubscribeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ UNSUBSCRIBE ALL.
        /// </summary>
        public static string B_UnsubscribeAll {
            get {
                return ResourceManager.GetString("B_UnsubscribeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Updates.
        /// </summary>
        public static string B_Updates {
            get {
                return ResourceManager.GetString("B_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Web.
        /// </summary>
        public static string B_Web {
            get {
                return ResourceManager.GetString("B_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🆔 ID: {0}
        ///
        ///👤 Level: {1}
        ///
        ///📅 Registered on: {2}
        ///
        ///🗣 Language: {3}.
        /// </summary>
        public static string P_Account {
            get {
                return ResourceManager.GetString("P_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ ProtoBuild is already searching for updates, please wait a few minutes then retry.
        ///Started searching: {0} minute(s) ago
        ///
        ///Your choice: &lt;b&gt;{1}&lt;/b&gt;, &lt;b&gt;{2}&lt;/b&gt;.
        /// </summary>
        public static string P_AlreadySearching {
            get {
                return ResourceManager.GetString("P_AlreadySearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❕ Command aborted..
        /// </summary>
        public static string P_CmdAborted {
            get {
                return ResourceManager.GetString("P_CmdAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤐 Command not found. Use the interactive version,  press the button below..
        /// </summary>
        public static string P_CmdNotFound {
            get {
                return ResourceManager.GetString("P_CmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing &lt;b&gt;{0}&lt;/b&gt; latest BuildLab for each ring:
        ///
        ///{1}.
        /// </summary>
        public static string P_DetailedUpdates {
            get {
                return ResourceManager.GetString("P_DetailedUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is expired (too old). Click below to start again..
        /// </summary>
        public static string P_Expired {
            get {
                return ResourceManager.GetString("P_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi &lt;a href=&quot;tg://user?id={0}&quot;&gt;{1}&lt;/a&gt; [ID: &lt;code&gt;{0}&lt;/code&gt;] (ADMIN),
        ///this is the Start page, below there are a few commands you can use..
        /// </summary>
        public static string P_HelpAdmin {
            get {
                return ResourceManager.GetString("P_HelpAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi master of bots [ID: &lt;code&gt;{0}&lt;/code&gt;],
        ///do what you need to do..
        /// </summary>
        public static string P_HelpCreator {
            get {
                return ResourceManager.GetString("P_HelpCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, this is the Start page, below there are a few commands you can use..
        /// </summary>
        public static string P_HelpGroup {
            get {
                return ResourceManager.GetString("P_HelpGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi &lt;a href=&quot;tg://user?id={0}&quot;&gt;{1}&lt;/a&gt; [ID: &lt;code&gt;{0}&lt;/code&gt;] (MOD),
        ///this is the Start page, below there are a few commands you can use..
        /// </summary>
        public static string P_HelpMod {
            get {
                return ResourceManager.GetString("P_HelpMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi &lt;a href=&quot;tg://user?id={0}&quot;&gt;{1}&lt;/a&gt; [ID: &lt;code&gt;{0}&lt;/code&gt;],
        ///this is the Start page, below there are a few commands you can use..
        /// </summary>
        public static string P_HelpUser {
            get {
                return ResourceManager.GetString("P_HelpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can select the display language.
        ///
        ///🗣 Selected language: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string P_Language {
            get {
                return ResourceManager.GetString("P_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 {0} New &lt;b&gt;{1}&lt;/b&gt; update! 💍 &lt;b&gt;{2}&lt;/b&gt; ({3})
        ///.
        /// </summary>
        public static string P_NewUpdateFound {
            get {
                return ResourceManager.GetString("P_NewUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📣 &lt;b&gt;Build Lab Extended&lt;/b&gt;:
        ///&lt;code&gt;{0}&lt;/code&gt;
        ///.
        /// </summary>
        public static string P_NewUpdateFoundBLE {
            get {
                return ResourceManager.GetString("P_NewUpdateFoundBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➡️ &lt;b&gt;Description&lt;/b&gt;:
        ///{0}.
        /// </summary>
        public static string P_NewUpdateFoundDE {
            get {
                return ResourceManager.GetString("P_NewUpdateFoundDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➡️ &lt;b&gt;Title&lt;/b&gt;:
        ///{0}
        ///.
        /// </summary>
        public static string P_NewUpdateFoundTitle {
            get {
                return ResourceManager.GetString("P_NewUpdateFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you can select each device family and ring and check for updates.
        /// </summary>
        public static string P_Search {
            get {
                return ResourceManager.GetString("P_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Searching updates done..
        /// </summary>
        public static string P_SearchCompleted {
            get {
                return ResourceManager.GetString("P_SearchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Search updates now!&quot; to start searching.
        ///Your choice: &lt;b&gt;{0}&lt;/b&gt;, &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        public static string P_SearchConfirm {
            get {
                return ResourceManager.GetString("P_SearchConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I&apos;m searching for updates. I&apos;ll notify you when the searches completes.
        /// </summary>
        public static string P_SearchingNow {
            get {
                return ResourceManager.GetString("P_SearchingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected device family: &lt;b&gt;{0}&lt;/b&gt;
        ///Choose a ring..
        /// </summary>
        public static string P_SearchRing {
            get {
                return ResourceManager.GetString("P_SearchRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select which device family to subscribe to. Remember that you&apos;ll get notified for all rings of the selected device family..
        /// </summary>
        public static string P_Subscribe {
            get {
                return ResourceManager.GetString("P_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can select the device family for which display the latest BuildLab..
        /// </summary>
        public static string P_Updates {
            get {
                return ResourceManager.GetString("P_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the interactive version, press the button below..
        /// </summary>
        public static string P_UseInteractiveVersion {
            get {
                return ResourceManager.GetString("P_UseInteractiveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all applicable rings.
        /// </summary>
        public static string W_AllApplicableRings {
            get {
                return ResourceManager.GetString("W_AllApplicableRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all rings.
        /// </summary>
        public static string W_AllRings {
            get {
                return ResourceManager.GetString("W_AllRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everything.
        /// </summary>
        public static string W_Everything {
            get {
                return ResourceManager.GetString("W_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete command!.
        /// </summary>
        public static string Z_CommandIncomplete {
            get {
                return ResourceManager.GetString("Z_CommandIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check completed..
        /// </summary>
        public static string Z_DBCheckCompleted {
            get {
                return ResourceManager.GetString("Z_DBCheckCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if migration is needed....
        /// </summary>
        public static string Z_DBCheckingMigration {
            get {
                return ResourceManager.GetString("Z_DBCheckingMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Connection opened!.
        /// </summary>
        public static string Z_DBConnectionOpened {
            get {
                return ResourceManager.GetString("Z_DBConnectionOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DB tables....
        /// </summary>
        public static string Z_DBCreatingTables {
            get {
                return ResourceManager.GetString("Z_DBCreatingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed..
        /// </summary>
        public static string Z_DBMigrationCompleted {
            get {
                return ResourceManager.GetString("Z_DBMigrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No migration is needed..
        /// </summary>
        public static string Z_DBNoMigration {
            get {
                return ResourceManager.GetString("Z_DBNoMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database store version is too new..
        /// </summary>
        public static string Z_DBStoreIsTooNew {
            get {
                return ResourceManager.GetString("Z_DBStoreIsTooNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running DB migration (to version: {0}).
        /// </summary>
        public static string Z_RunningMigration {
            get {
                return ResourceManager.GetString("Z_RunningMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running post upgrade actions (num: {0}).
        /// </summary>
        public static string Z_RunningPostUpgrade {
            get {
                return ResourceManager.GetString("Z_RunningPostUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search started.
        /// </summary>
        public static string Z_SearchStarted {
            get {
                return ResourceManager.GetString("Z_SearchStarted", resourceCulture);
            }
        }
    }
}
